/**
 * 셸 자동완성 스크립트 생성(v2) — `adde completion <bash|zsh>`.
 * COMMAND_SPECS(SSOT)에서 명령·하위명령·플래그를 전부 파생한다(T021 완료 기준 "자동완성·usage·
 * 파서·디스패치 4소비자가 신규 표면으로 자동 갱신") — 그룹 명령(subs 보유) 목록·각 하위명령의
 * 플래그 이름을 하드코딩하지 않고 `visibleCommands()`/`findSub()`/`flagNames()` 로만 읽는다.
 * proj/session 동적 완성은 `${ADDE_HOME:-~/.config/adde}/projects` 를 스캔한다.
 *
 * **범위 고지(spec "범위 외" · CUT-006)**: 플래그 *이름* 완성까지만 제공한다 — 값 플래그의 enum
 * 완성(`--perm-tier acp|autopass` 등, `FLAG_VALUES` 참조)과 프로젝트 설정 점표기 키 완성은 FR-042
 * 가 요구하지 않는 순수 입력 편의 기능이라 spec.md "범위 외"·scope.md CUT-006 에 이미 명시적으로
 * 제외됐다(침묵 축소 아님).
 */
import { visibleCommands, findCommand, flagNames } from "./spec.js";
import type { CommandSpec, SubSpec } from "./spec.js";
import { RECOMMENDED_ALIASES } from "./alias.js";

export const SUPPORTED_SHELLS = ["bash", "zsh"] as const;
export type CompletionShell = (typeof SUPPORTED_SHELLS)[number];

const COMPLETION_TARGETS = [...new Set(["adde", ...RECOMMENDED_ALIASES])].join(" ");

function commandNames(): string {
  return visibleCommands()
    .map((c) => c.name)
    .join(" ");
}

function subNames(cmdName: string): string {
  return (findCommand(cmdName)?.subs ?? []).map((s) => s.name).join(" ");
}

/** subs 를 보유한(그룹) 명령 목록 — 하드코딩 대신 COMMAND_SPECS 에서 직접 파생. */
function groupCommands(): CommandSpec[] {
  return visibleCommands().filter((c) => c.subs && c.subs.length > 0);
}

/** subs 가 없는(단일 표면) 명령 중 플래그가 1개 이상인 것 — 완성할 플래그가 있는 것만 대상. */
function flatCommandsWithFlags(): CommandSpec[] {
  return visibleCommands().filter((c) => (!c.subs || c.subs.length === 0) && c.flags.length > 0);
}

function bashScript(): string {
  const commands = commandNames();
  const groupCases = groupCommands()
    .map((c) => {
      const subCases = (c.subs ?? [])
        .map(
          (s: SubSpec) =>
            `          ${s.name}) COMPREPLY=( $(compgen -W "${flagNames(s).join(" ")}" -- "$cur") );;`,
        )
        .join("\n");
      return `    ${c.name})
      if [[ "$cur" == -* ]]; then
        case "\${COMP_WORDS[2]}" in
${subCases}
        esac
      else
        COMPREPLY=( $(compgen -W "${subNames(c.name)}" -- "$cur") )
      fi
      return;;`;
    })
    .join("\n");
  const flatCases = flatCommandsWithFlags()
    .map(
      (c) => `    ${c.name})
      [[ "$cur" == -* ]] && COMPREPLY=( $(compgen -W "${flagNames(c).join(" ")}" -- "$cur") )
      return;;`,
    )
    .join("\n");
  return `# adde bash completion(v2) — generated by \`adde completion bash\`
_adde_projects() {
  local base="\${ADDE_HOME:-$HOME/.config/adde}/projects" d
  [ -d "$base" ] || return 0
  for d in "$base"/*/; do [ -e "\${d}project.conf" ] && basename "$d"; done 2>/dev/null
}
_adde() {
  local cur cword
  cur="\${COMP_WORDS[COMP_CWORD]}"
  cword=\${COMP_CWORD}
  local commands="${commands}"
  if [ "$cword" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "$commands" -- "$cur") )
    return
  fi
  local cmd="\${COMP_WORDS[1]}"
  if [ "$cword" -eq 2 ] && [[ "$cur" != -* ]]; then
    COMPREPLY=( $(compgen -W "$(_adde_projects)" -- "$cur") )
  fi
  case "$cmd" in
${groupCases}
${flatCases}
  esac
}
complete -F _adde ${COMPLETION_TARGETS}
`;
}

function zshScript(): string {
  const commandDescribe = visibleCommands()
    .map((c) => `'${c.name}:${c.desc ?? c.name}'`)
    .join(" ");
  const targets = ["adde", ...RECOMMENDED_ALIASES].join(" ");
  const groupCases = groupCommands()
    .map((c) => {
      const subCases = (c.subs ?? [])
        .map(
          (s: SubSpec) =>
            `        ${s.name}) _values '${c.name} ${s.name} flag' ${flagNames(s).join(" ")} ;;`,
        )
        .join("\n");
      return `    ${c.name})
      if [[ "$cur" == -* ]]; then
        case "\${words[3]}" in
${subCases}
        esac
      else
        _values '${c.name} subcommand' ${subNames(c.name)}
      fi
      ;;`;
    })
    .join("\n");
  const flatCases = flatCommandsWithFlags()
    .map(
      (c) =>
        `    ${c.name}) [[ "$cur" == -* ]] && _values '${c.name} flag' ${flagNames(c).join(" ")} ;;`,
    )
    .join("\n");
  return `#compdef ${targets}
# adde zsh completion(v2) — generated by \`adde completion zsh\`
_adde_projects() {
  local base="\${ADDE_HOME:-$HOME/.config/adde}/projects"
  local -a p
  for d in "$base"/*/(/N); do [ -e "\${d}project.conf" ] && p+=("\${\${d:h}:t}"); done
  compadd -- $p
}
_adde() {
  local -a commands
  local cur="\${words[CURRENT]}"
  commands=(${commandDescribe})
  if (( CURRENT == 2 )); then
    _describe 'adde command' commands
    return
  fi
  case "\${words[2]}" in
${groupCases}
${flatCases}
  esac
}
compdef _adde ${targets}
`;
}

export function completionScript(shell: string): string | null {
  if (shell === "bash") return bashScript();
  if (shell === "zsh") return zshScript();
  return null;
}
