/**
 * 셸 자동완성 스크립트 생성 — `adde completion <bash|zsh>`.
 * COMMAND_SPECS(SSOT)에서 명령·플래그·위치인자 종류를 파생하므로, 스펙에 추가하면
 * 자동완성이 함께 갱신된다. bash·zsh(맥 기본) 지원. adde + 짧은 별칭(ad·add) 등록.
 *
 * 동적 완성(proj/lane 이름)은 node 스폰 없이 셸에서 설정 base(`${ADDE_HOME:-~/.config/adde}`)를
 * 직접 스캔한다(즉응성). enum 플래그 값·디렉터리 플래그·zsh 명령 설명도 스펙에서 생성.
 */
import {
  visibleCommands,
  LANE_ADD_FLAGS,
  LANE_SUBS,
  FLAG_VALUES,
  DIR_FLAGS,
  GLOBAL_FLAGS,
} from "./spec.js";
import type { CommandSpec } from "./spec.js";
import { RECOMMENDED_ALIASES } from "./alias.js";

export const SUPPORTED_SHELLS = ["bash", "zsh"] as const;
export type CompletionShell = (typeof SUPPORTED_SHELLS)[number];

/** adde + 짧은 별칭을 완성 대상으로 등록(공백 구분, 중복 제거). */
const COMPLETION_TARGETS = [...new Set(["adde", ...RECOMMENDED_ALIASES])].join(" ");

/** 최상위 명령 중 자동완성에서 특수 처리하는(제네릭 case 제외) 이름. */
const SPECIAL = new Set(["lane", "completion", "alias"]);

function commandNames(): string {
  return visibleCommands()
    .map((c) => c.name)
    .join(" ");
}

/** 제네릭(위치인자 proj/lane) 명령 목록 — lane/completion/alias 제외. */
function genericCommands(): CommandSpec[] {
  return visibleCommands().filter((c) => !SPECIAL.has(c.name));
}

// ── bash ────────────────────────────────────────────────────────────────

/** 값 플래그(enum·디렉터리) 뒤 완성 case (bash). */
function bashFlagValueCases(): string {
  const lines = Object.entries(FLAG_VALUES).map(
    ([flag, vals]) =>
      `    ${flag}) COMPREPLY=( $(compgen -W "${vals.join(" ")}" -- "$cur") ); return;;`,
  );
  lines.push(`    ${DIR_FLAGS.join("|")}) COMPREPLY=( $(compgen -d -- "$cur") ); return;;`);
  return lines.join("\n");
}

/** 제네릭 명령별 위치인자·플래그 완성 case (bash). */
function bashCommandCases(): string {
  return genericCommands()
    .map((c) => {
      const flags = c.flags.join(" ");
      const withFlags = (base: string): string => (flags ? `${base} ${flags}` : base);
      const pos = c.positional ?? [];
      if (pos[0] === "proj" && pos[1] === "lane") {
        const tail = flags
          ? `\n      COMPREPLY=( $(compgen -W "${flags}" -- "$cur") ); return;;`
          : `\n      ;;`;
        return `    ${c.name})
      if [ "$cword" -eq 2 ]; then COMPREPLY=( $(compgen -W "$(_adde_projects)" -- "$cur") ); return; fi
      if [ "$cword" -eq 3 ]; then COMPREPLY=( $(compgen -W "${withFlags('$(_adde_lanes "${COMP_WORDS[2]}")')}" -- "$cur") ); return; fi${tail}`;
      }
      if (pos[0] === "proj") {
        const tail = flags
          ? `\n      COMPREPLY=( $(compgen -W "${flags}" -- "$cur") ); return;;`
          : `\n      ;;`;
        return `    ${c.name})
      if [ "$cword" -eq 2 ]; then COMPREPLY=( $(compgen -W "${withFlags("$(_adde_projects)")}" -- "$cur") ); return; fi${tail}`;
      }
      return null;
    })
    .filter((s): s is string => s !== null)
    .join("\n");
}

function bashScript(): string {
  const commands = commandNames();
  const globals = GLOBAL_FLAGS.join(" ");
  const laneSubs = LANE_SUBS.join(" ");
  const laneAddFlags = LANE_ADD_FLAGS.join(" ");
  const aliasSuggest = RECOMMENDED_ALIASES.join(" ");
  return `# adde bash completion — generated by \`adde completion bash\`
# 설치: adde completion bash > /usr/local/etc/bash_completion.d/adde  (또는 ~/.bashrc 에서 source)
# proj/lane 동적 완성은 \${ADDE_HOME:-~/.config/adde} 를 스캔한다.
_adde_projects() {
  local base="\${ADDE_HOME:-$HOME/.config/adde}" d
  [ -d "$base" ] || return 0
  for d in "$base"/*/; do [ -d "\${d}lanes.d" ] && basename "$d"; done 2>/dev/null
}
_adde_lanes() {
  local base="\${ADDE_HOME:-$HOME/.config/adde}" f
  [ -n "$1" ] || return 0
  for f in "$base/$1/lanes.d"/*.conf; do [ -e "$f" ] && basename "$f" .conf; done 2>/dev/null
}
_adde() {
  local cur prev cword
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  cword=\${COMP_CWORD}
  case "$prev" in
${bashFlagValueCases()}
  esac
  local commands="${commands}"
  local cmd="\${COMP_WORDS[1]}"
  if [ "$cword" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "\${commands} ${globals}" -- "$cur") )
    return
  fi
  case "$cmd" in
    lane)
      if [ "$cword" -eq 2 ]; then COMPREPLY=( $(compgen -W "${laneSubs}" -- "$cur") ); return; fi
      local sub="\${COMP_WORDS[2]}"
      case "$sub" in
        add)
          if [ "$cword" -eq 3 ]; then COMPREPLY=( $(compgen -W "$(_adde_projects)" -- "$cur") ); return; fi
          if [ "$cword" -ge 5 ] || [ "\${cur:0:1}" = "-" ]; then COMPREPLY=( $(compgen -W "${laneAddFlags}" -- "$cur") ); return; fi
          ;;
        ls)
          if [ "$cword" -eq 3 ]; then COMPREPLY=( $(compgen -W "$(_adde_projects)" -- "$cur") ); return; fi ;;
        show|rm)
          if [ "$cword" -eq 3 ]; then COMPREPLY=( $(compgen -W "$(_adde_projects)" -- "$cur") ); return; fi
          if [ "$cword" -eq 4 ]; then COMPREPLY=( $(compgen -W "$(_adde_lanes "\${COMP_WORDS[3]}")" -- "$cur") ); return; fi ;;
      esac
      return;;
    completion) COMPREPLY=( $(compgen -W "${SUPPORTED_SHELLS.join(" ")}" -- "$cur") ); return;;
    alias) COMPREPLY=( $(compgen -W "${aliasSuggest}" -- "$cur") ); return;;
${bashCommandCases()}
  esac
}
complete -F _adde ${COMPLETION_TARGETS}
`;
}

// ── zsh ─────────────────────────────────────────────────────────────────

/** 값 플래그(enum·디렉터리) 뒤 완성 case (zsh). */
function zshFlagValueCases(): string {
  const lines = Object.entries(FLAG_VALUES).map(
    ([flag, vals]) => `    ${flag}) compadd ${vals.join(" ")}; return;;`,
  );
  lines.push(`    ${DIR_FLAGS.join("|")}) _files -/; return;;`);
  return lines.join("\n");
}

/** 제네릭 명령별 위치인자·플래그 완성 case (zsh). */
function zshCommandCases(): string {
  return genericCommands()
    .map((c) => {
      const flagsVals = c.flags.length > 0 ? `; _values 'option' ${c.flags.join(" ")}` : "";
      const pos = c.positional ?? [];
      if (pos[0] === "proj" && pos[1] === "lane") {
        return `    ${c.name})
      if (( CURRENT == 3 )); then _adde_projects; return; fi
      if (( CURRENT == 4 )); then _adde_lanes "\${words[3]}"${flagsVals}; return; fi${flagsVals ? `\n      _values 'option' ${c.flags.join(" ")} ;;` : "\n      ;;"}`;
      }
      if (pos[0] === "proj") {
        return `    ${c.name})
      if (( CURRENT == 3 )); then _adde_projects${flagsVals}; return; fi${flagsVals ? `\n      _values 'option' ${c.flags.join(" ")} ;;` : "\n      ;;"}`;
      }
      return null;
    })
    .filter((s): s is string => s !== null)
    .join("\n");
}

function zshScript(): string {
  const commandDescribe = visibleCommands()
    .map((c) => `'${c.name}:${c.desc ?? c.name}'`)
    .join(" ");
  const laneSubs = LANE_SUBS.join(" ");
  const laneAddFlags = LANE_ADD_FLAGS.join(" ");
  const aliasSuggest = RECOMMENDED_ALIASES.join(" ");
  const targets = ["adde", ...RECOMMENDED_ALIASES].join(" ");
  return `#compdef ${targets}
# adde zsh completion — generated by \`adde completion zsh\`
# 설치: adde completion zsh > "\${fpath[1]}/_adde"  (또는 compinit 후 이 스크립트를 source)
# proj/lane 동적 완성은 \${ADDE_HOME:-~/.config/adde} 를 스캔한다.
_adde_projects() {
  local base="\${ADDE_HOME:-$HOME/.config/adde}" d
  local -a p
  for d in "$base"/*/lanes.d(/N); do p+=("\${\${d:h}:t}"); done
  compadd -- $p
}
_adde_lanes() {
  local base="\${ADDE_HOME:-$HOME/.config/adde}" f
  local -a l
  [ -n "$1" ] || return 0
  for f in "$base/$1/lanes.d"/*.conf(N); do l+=("\${\${f:t}:r}"); done
  compadd -- $l
}
_adde() {
  local -a commands
  commands=(${commandDescribe})
  case "\${words[CURRENT-1]}" in
${zshFlagValueCases()}
  esac
  if (( CURRENT == 2 )); then
    _describe 'adde command' commands
    return
  fi
  case "\${words[2]}" in
    lane)
      if (( CURRENT == 3 )); then _values 'lane subcommand' ${laneSubs}; return; fi
      case "\${words[3]}" in
        add)
          if (( CURRENT == 4 )); then _adde_projects; return; fi
          _values 'option' ${laneAddFlags} ;;
        ls)
          if (( CURRENT == 4 )); then _adde_projects; return; fi ;;
        show|rm)
          if (( CURRENT == 4 )); then _adde_projects; return; fi
          if (( CURRENT == 5 )); then _adde_lanes "\${words[4]}"; return; fi ;;
      esac
      ;;
    completion) _values 'shell' ${SUPPORTED_SHELLS.join(" ")} ;;
    alias) compadd ${aliasSuggest} ;;
${zshCommandCases()}
  esac
}
compdef _adde ${targets}
`;
}

/** 지정 셸의 자동완성 스크립트 텍스트. 미지원 셸은 null. */
export function completionScript(shell: string): string | null {
  if (shell === "bash") return bashScript();
  if (shell === "zsh") return zshScript();
  return null;
}
