/**
 * 셸 자동완성 스크립트 생성 — `adde completion <bash|zsh>`.
 * COMMAND_SPECS(SSOT)에서 명령·플래그를 파생하므로, 스펙에 명령/플래그를 추가하면
 * 자동완성이 함께 갱신된다. bash·zsh(맥 기본) 지원. 두 진입점(adde·add) 모두 등록.
 */
import { visibleCommands, LANE_ADD_FLAGS, LANE_SUBS, GLOBAL_FLAGS } from "./spec.js";

export const SUPPORTED_SHELLS = ["bash", "zsh"] as const;
export type CompletionShell = (typeof SUPPORTED_SHELLS)[number];

/** 명령별 옵션 플래그 목록(공백 구분). lane 은 하위 명령에서 별도 처리. */
function commandFlags(): { name: string; flags: string }[] {
  return visibleCommands().map((c) => ({ name: c.name, flags: c.flags.join(" ") }));
}

function commandNames(): string {
  return visibleCommands()
    .map((c) => c.name)
    .join(" ");
}

/** bash 완성 스크립트 — 1번째 인자=명령, lane 하위·명령별 플래그·completion 셸 완성. */
function bashScript(): string {
  const commands = commandNames();
  const globals = GLOBAL_FLAGS.join(" ");
  const laneSubs = LANE_SUBS.join(" ");
  const laneAddFlags = LANE_ADD_FLAGS.join(" ");
  const perCmdCases = commandFlags()
    .filter((c) => c.flags.length > 0 && c.name !== "lane")
    .map((c) => `    ${c.name}) COMPREPLY=( $(compgen -W "${c.flags}" -- "$cur") ); return;;`)
    .join("\n");
  return `# adde bash completion — generated by \`adde completion bash\`
# 설치: adde completion bash > /usr/local/etc/bash_completion.d/adde  (또는 ~/.bashrc 에서 source)
_adde() {
  local cur prev cword
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  cword=\${COMP_CWORD}
  local commands="${commands}"
  local cmd="\${COMP_WORDS[1]}"
  if [ "$cword" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "\${commands} ${globals}" -- "$cur") )
    return
  fi
  case "$cmd" in
    lane)
      if [ "$cword" -eq 2 ]; then
        COMPREPLY=( $(compgen -W "${laneSubs}" -- "$cur") ); return
      fi
      if [ "\${COMP_WORDS[2]}" = "add" ]; then
        COMPREPLY=( $(compgen -W "${laneAddFlags}" -- "$cur") ); return
      fi
      ;;
    completion) COMPREPLY=( $(compgen -W "${SUPPORTED_SHELLS.join(" ")}" -- "$cur") ); return;;
${perCmdCases}
  esac
}
complete -F _adde adde add
`;
}

/** zsh 완성 스크립트 — compinit 후 source 하면 compdef 로 등록. */
function zshScript(): string {
  const commands = visibleCommands()
    .map((c) => `'${c.name}'`)
    .join(" ");
  const laneSubs = LANE_SUBS.join(" ");
  const laneAddFlags = LANE_ADD_FLAGS.join(" ");
  const perCmdCases = commandFlags()
    .filter((c) => c.flags.length > 0 && c.name !== "lane")
    .map((c) => `      ${c.name}) _values 'option' ${c.flags.split(" ").join(" ")} ;;`)
    .join("\n");
  return `#compdef adde add
# adde zsh completion — generated by \`adde completion zsh\`
# 설치: adde completion zsh > "\${fpath[1]}/_adde"  (또는 compinit 후 이 스크립트를 source)
_adde() {
  local -a commands
  commands=(${commands})
  if (( CURRENT == 2 )); then
    _describe 'adde command' commands
    return
  fi
  case "\${words[2]}" in
    lane)
      if (( CURRENT == 3 )); then _values 'lane subcommand' ${laneSubs}; return; fi
      if [[ "\${words[3]}" == add ]]; then _values 'option' ${laneAddFlags}; return; fi
      ;;
    completion) _values 'shell' ${SUPPORTED_SHELLS.join(" ")} ;;
${perCmdCases}
  esac
}
compdef _adde adde add
`;
}

/** 지정 셸의 자동완성 스크립트 텍스트. 미지원 셸은 null. */
export function completionScript(shell: string): string | null {
  if (shell === "bash") return bashScript();
  if (shell === "zsh") return zshScript();
  return null;
}
