/**
 * Task 전이 표 전사(FR-004, FR-023) — the workflow contract "Task transition table" 45행.
 * 이름 열은 백틱 없이, 서술 열(`fromText`·`condition`)은 계약 셀 원문 그대로(백틱 포함).
 * 행 ID 규칙은 design.md "행 ID 규칙" — `id = fromKey + ">" + to + ":" + event`.
 */
import type { TaskStateName } from "../task-state.js";

export interface TransitionRowData<S extends string> {
  readonly id: string;
  /** 계약 From 셀 원문(백틱 포함, "—" 포함). */
  readonly fromText: string;
  /** 출발 상태 전개(생성 행은 []). */
  readonly from: readonly S[];
  readonly to: S;
  readonly event: string;
  /** 계약 Condition 셀 원문. */
  readonly condition: string;
  /** 계약이 명시한 동반 이벤트. */
  readonly companions: readonly string[];
}

const ALL_NONTERMINAL_TASK_STATES: readonly TaskStateName[] = [
  "DRAFT",
  "VALIDATING",
  "WAITING_INPUT",
  "READY",
  "SCHEDULED",
  "RUNNING",
  "WAITING_CONFIRMATION",
  "RETRY_WAIT",
  "BLOCKED",
  "BLOCKED_AWAITING_HUMAN",
];

const NONTERMINAL_EXCEPT_WAITING_CONFIRMATION: readonly TaskStateName[] =
  ALL_NONTERMINAL_TASK_STATES.filter((s) => s !== "WAITING_CONFIRMATION");

export const TASK_TRANSITION_ROWS = [
  {
    id: "NONE>DRAFT:task_created",
    fromText: "—",
    from: [],
    to: "DRAFT",
    event: "task_created",
    condition: "A validated TaskDraft is committed as a Task",
    companions: [],
  },
  {
    id: "DRAFT>VALIDATING:task_validation_started",
    fromText: "`DRAFT`",
    from: ["DRAFT"],
    to: "VALIDATING",
    event: "task_validation_started",
    condition: "Validation begins",
    companions: [],
  },
  {
    id: "VALIDATING>WAITING_INPUT:task_input_requested",
    fromText: "`VALIDATING`",
    from: ["VALIDATING"],
    to: "WAITING_INPUT",
    event: "task_input_requested",
    condition: "Required schema fields are missing",
    companions: [],
  },
  {
    id: "VALIDATING>READY:task_validated",
    fromText: "`VALIDATING`",
    from: ["VALIDATING"],
    to: "READY",
    event: "task_validated",
    condition:
      'Schema and policy validation succeeded; for a `dependencies_complete@1` Trigger, every dependency is non-terminal or satisfied ("Terminal semantics and completion aggregation")',
    companions: [],
  },
  {
    id: "VALIDATING>BLOCKED:task_blocked",
    fromText: "`VALIDATING`",
    from: ["VALIDATING"],
    to: "BLOCKED",
    event: "task_blocked",
    condition:
      'Descriptor `(id, version)` unknown, dependency unsatisfiable, or the approval surface was refused ("TaskPolicy" "Approval surface")',
    companions: [],
  },
  {
    id: "VALIDATING>FAILED:task_validation_failed",
    fromText: "`VALIDATING`",
    from: ["VALIDATING"],
    to: "FAILED",
    event: "task_validation_failed",
    condition: "Input is structurally invalid and not repairable by input collection",
    companions: [],
  },
  {
    id: "WAITING_INPUT>VALIDATING:task_input_received",
    fromText: "`WAITING_INPUT`",
    from: ["WAITING_INPUT"],
    to: "VALIDATING",
    event: "task_input_received",
    condition: "Answers ingested; revalidate",
    companions: [],
  },
  {
    id: "WAITING_INPUT>EXPIRED:task_expired",
    fromText: "`WAITING_INPUT`",
    from: ["WAITING_INPUT"],
    to: "EXPIRED",
    event: "task_expired",
    condition: "`policy.expiresAt` passed",
    companions: [],
  },
  {
    id: "READY>SCHEDULED:task_scheduled",
    fromText: "`READY`",
    from: ["READY"],
    to: "SCHEDULED",
    event: "task_scheduled",
    condition:
      'A durable trigger occurrence is persisted for the Task \u2014 from the schedule for `at@1`/`after@1`, or, for `dependencies_complete@1` and `signal@1`, derived from the committed causing event in the same commit as that event, or, for a `dependencies_complete@1` Task that reaches `READY` after its dependencies were satisfied, in the commit where it reaches `READY` ("Occurrence ID derivation")',
    companions: [],
  },
  {
    id: "READY>RUNNING:task_started",
    fromText: "`READY`",
    from: ["READY"],
    to: "RUNNING",
    event: "task_started",
    condition: "Trigger kind is `immediate@1` and the executor claimed the Task",
    companions: [],
  },
  {
    id: "READY>WAITING_CONFIRMATION:task_waiting_confirmation",
    fromText: "`READY`",
    from: ["READY"],
    to: "WAITING_CONFIRMATION",
    event: "task_waiting_confirmation",
    condition: "`confirmation@1` request was persisted to the outbox",
    companions: [],
  },
  {
    id: "READY>BLOCKED_AWAITING_HUMAN:task_awaiting_human",
    fromText: "`READY`",
    from: ["READY"],
    to: "BLOCKED_AWAITING_HUMAN",
    event: "task_awaiting_human",
    condition: "`policy.approvalRequiredBeforeExecute`, or unattended eligibility check refused",
    companions: [],
  },
  {
    id: "READY>BLOCKED:task_blocked",
    fromText: "`READY`",
    from: ["READY"],
    to: "BLOCKED",
    event: "task_blocked",
    condition: "Dependency became unsatisfied before dispatch",
    companions: [],
  },
  {
    id: "READY>EXPIRED:task_expired",
    fromText: "`READY`",
    from: ["READY"],
    to: "EXPIRED",
    event: "task_expired",
    condition: "`policy.expiresAt` passed before an attempt or effect started",
    companions: [],
  },
  {
    id: "SCHEDULED>RUNNING:task_started",
    fromText: "`SCHEDULED`",
    from: ["SCHEDULED"],
    to: "RUNNING",
    event: "task_started",
    condition: "A trigger occurrence fired and the executor claimed the Task",
    companions: [],
  },
  {
    id: "SCHEDULED>WAITING_CONFIRMATION:task_waiting_confirmation",
    fromText: "`SCHEDULED`",
    from: ["SCHEDULED"],
    to: "WAITING_CONFIRMATION",
    event: "task_waiting_confirmation",
    condition: "A scheduled confirmation request became due and was enqueued",
    companions: [],
  },
  {
    id: "SCHEDULED>BLOCKED_AWAITING_HUMAN:task_awaiting_human",
    fromText: "`SCHEDULED`",
    from: ["SCHEDULED"],
    to: "BLOCKED_AWAITING_HUMAN",
    event: "task_awaiting_human",
    condition: "Due in an unattended window while unattended eligibility is not satisfied",
    companions: [],
  },
  {
    id: "SCHEDULED>READY:task_unscheduled",
    fromText: "`SCHEDULED`",
    from: ["SCHEDULED"],
    to: "READY",
    event: "task_unscheduled",
    condition: "Trigger occurrence was invalidated by a reschedule and the Task remains eligible",
    companions: [],
  },
  {
    id: "SCHEDULED>EXPIRED:task_expired",
    fromText: "`SCHEDULED`",
    from: ["SCHEDULED"],
    to: "EXPIRED",
    event: "task_expired",
    condition: "`policy.expiresAt` passed before firing",
    companions: [],
  },
  {
    id: "RUNNING>COMPLETED:task_completed",
    fromText: "`RUNNING`",
    from: ["RUNNING"],
    to: "COMPLETED",
    event: "task_completed",
    condition:
      'Executor returned `status: "completed"` with evidence, and the outputs validate against the descriptor\'s declared outputs ("Task result and input binding")',
    companions: [],
  },
  {
    id: "RUNNING>RETRY_WAIT:task_retry_wait",
    fromText: "`RUNNING`",
    from: ["RUNNING"],
    to: "RETRY_WAIT",
    event: "task_retry_wait",
    condition:
      "The open attempt failed retryably — including `dispatch_orphaned`, `attempt_timeout` and `dispatch_withdrawn` — `attemptNo < policy.retry.maxAttempts`, and `policy.expiresAt` has not passed",
    companions: [],
  },
  {
    id: "RUNNING>BLOCKED_AWAITING_HUMAN:task_awaiting_human",
    fromText: "`RUNNING`",
    from: ["RUNNING"],
    to: "BLOCKED_AWAITING_HUMAN",
    event: "task_awaiting_human",
    condition:
      '`policy.expiresAt` has not passed, and the permission gate denied, the executor returned `status: "blocked"`, the dispatcher refused the request — unattended without `toolScope`, a stopped or detached session, or a session or binding it cannot resolve — or an effect of the open attempt was dead-lettered — an outbox row, delivery or agent dispatch, that exhausted its budget, or an orphaned or withdrawn dispatch with no attempt left — so its retry-or-discard decision is what the Task waits on',
    companions: [],
  },
  {
    id: "RUNNING>FAILED:task_failed",
    fromText: "`RUNNING`",
    from: ["RUNNING"],
    to: "FAILED",
    event: "task_failed",
    condition:
      "`policy.expiresAt` has not passed, and the open attempt failed non-retryably, or retryably with no attempt left, other than by an orphaned or withdrawn dispatch",
    companions: [],
  },
  {
    id: "RUNNING>EXPIRED:task_expired",
    fromText: "`RUNNING`",
    from: ["RUNNING"],
    to: "EXPIRED",
    event: "task_expired",
    condition:
      "The open attempt ended without completing after `policy.expiresAt` passed — including its own effect abandoned at the pre-send recheck for validity — so no further attempt may start; the payload carries the attempt's actual outcome",
    companions: [],
  },
  {
    id: "RETRY_WAIT>READY:task_retry_ready",
    fromText: "`RETRY_WAIT`",
    from: ["RETRY_WAIT"],
    to: "READY",
    event: "task_retry_ready",
    condition: "Retry delay elapsed and no trigger occurrence is required",
    companions: [],
  },
  {
    id: "RETRY_WAIT>SCHEDULED:task_scheduled",
    fromText: "`RETRY_WAIT`",
    from: ["RETRY_WAIT"],
    to: "SCHEDULED",
    event: "task_scheduled",
    condition: "Retry delay elapsed and a new occurrence was persisted",
    companions: [],
  },
  {
    id: "RETRY_WAIT>FAILED:task_failed",
    fromText: "`RETRY_WAIT`",
    from: ["RETRY_WAIT"],
    to: "FAILED",
    event: "task_failed",
    condition: "Retry budget exhausted before the delay elapsed, or retries were abandoned",
    companions: [],
  },
  {
    id: "RETRY_WAIT>EXPIRED:task_expired",
    fromText: "`RETRY_WAIT`",
    from: ["RETRY_WAIT"],
    to: "EXPIRED",
    event: "task_expired",
    condition: "`policy.expiresAt` passed before the next attempt",
    companions: [],
  },
  {
    id: "WAITING_CONFIRMATION>WAITING_CONFIRMATION:reminder_occurrence_emitted",
    fromText: "`WAITING_CONFIRMATION`",
    from: ["WAITING_CONFIRMATION"],
    to: "WAITING_CONFIRMATION",
    event: "reminder_occurrence_emitted",
    condition: "A reminder occurrence fired; state is unchanged",
    companions: [],
  },
  {
    id: "WAITING_CONFIRMATION>COMPLETED:confirmation_accepted",
    fromText: "`WAITING_CONFIRMATION`",
    from: ["WAITING_CONFIRMATION"],
    to: "COMPLETED",
    event: "confirmation_accepted",
    condition: "Valid accept signal, `human_local` provenance, revision matched",
    companions: [],
  },
  {
    id: "WAITING_CONFIRMATION>REJECTED:confirmation_rejected",
    fromText: "`WAITING_CONFIRMATION`",
    from: ["WAITING_CONFIRMATION"],
    to: "REJECTED",
    event: "confirmation_rejected",
    condition: "Valid reject signal, `human_local` provenance, revision matched",
    companions: [],
  },
  {
    id: "WAITING_CONFIRMATION>CANCELED:confirmation_cancelled",
    fromText: "`WAITING_CONFIRMATION`",
    from: ["WAITING_CONFIRMATION"],
    to: "CANCELED",
    event: "confirmation_cancelled",
    condition: "Valid cancel signal from an authorized actor, or the owning Work was canceled",
    companions: [],
  },
  {
    id: "WAITING_CONFIRMATION>EXPIRED:confirmation_expired",
    fromText: "`WAITING_CONFIRMATION`",
    from: ["WAITING_CONFIRMATION"],
    to: "EXPIRED",
    event: "confirmation_expired",
    condition: "Confirmation deadline passed with no valid decision",
    companions: [],
  },
  {
    id: "BLOCKED>VALIDATING:task_unblocked",
    fromText: "`BLOCKED`",
    from: ["BLOCKED"],
    to: "VALIDATING",
    event: "task_unblocked",
    condition:
      'The blocking condition was repaired; revalidate before any execution. Never for `blockReason: "approval_surface_refused"`',
    companions: [],
  },
  {
    id: "BLOCKED>CANCELED:task_canceled",
    fromText: "`BLOCKED`",
    from: ["BLOCKED"],
    to: "CANCELED",
    event: "task_canceled",
    condition: "Authorized cancellation",
    companions: [],
  },
  {
    id: "BLOCKED>EXPIRED:task_expired",
    fromText: "`BLOCKED`",
    from: ["BLOCKED"],
    to: "EXPIRED",
    event: "task_expired",
    condition: "`policy.expiresAt` passed while blocked",
    companions: [],
  },
  {
    id: "BLOCKED_AWAITING_HUMAN>READY:human_decision_granted",
    fromText: "`BLOCKED_AWAITING_HUMAN`",
    from: ["BLOCKED_AWAITING_HUMAN"],
    to: "READY",
    event: "human_decision_granted",
    condition:
      "The pending decision was granted by `human_local` actor; Task resumes from the point of interruption",
    companions: [],
  },
  {
    id: "BLOCKED_AWAITING_HUMAN>SCHEDULED:human_decision_granted",
    fromText: "`BLOCKED_AWAITING_HUMAN`",
    from: ["BLOCKED_AWAITING_HUMAN"],
    to: "SCHEDULED",
    event: "human_decision_granted",
    condition:
      'As above, and a new trigger occurrence was persisted — including every dead-letter retry, which is one new execution attempt beyond the retry budget from an occurrence the grant causes ("Dead-letter contract" rule 9)',
    companions: [],
  },
  {
    id: "BLOCKED_AWAITING_HUMAN>REJECTED:human_decision_denied",
    fromText: "`BLOCKED_AWAITING_HUMAN`",
    from: ["BLOCKED_AWAITING_HUMAN"],
    to: "REJECTED",
    event: "human_decision_denied",
    condition:
      "The pending decision was explicitly denied and the Task's remaining work is what was declined",
    companions: [],
  },
  {
    id: "BLOCKED_AWAITING_HUMAN>FAILED:task_failed",
    fromText: "`BLOCKED_AWAITING_HUMAN`",
    from: ["BLOCKED_AWAITING_HUMAN"],
    to: "FAILED",
    event: "task_failed",
    condition:
      "The pending decision was resolved in a way that leaves the Task nothing to do — a discarded dead letter that was the Task's only effect. `human_decision_denied` is appended in the same commit",
    companions: ["human_decision_denied"],
  },
  {
    id: "BLOCKED_AWAITING_HUMAN>EXPIRED:task_expired",
    fromText: "`BLOCKED_AWAITING_HUMAN`",
    from: ["BLOCKED_AWAITING_HUMAN"],
    to: "EXPIRED",
    event: "task_expired",
    condition: "`PendingDecision.expiresAt` or `policy.expiresAt` passed unanswered",
    companions: [],
  },
  {
    id: "BLOCKED_AWAITING_HUMAN>CANCELED:task_canceled",
    fromText: "`BLOCKED_AWAITING_HUMAN`",
    from: ["BLOCKED_AWAITING_HUMAN"],
    to: "CANCELED",
    event: "task_canceled",
    condition: "Authorized cancellation",
    companions: [],
  },
  {
    id: "ANY_NONTERMINAL_EXCEPT_WAITING_CONFIRMATION>CANCELED:task_canceled",
    fromText: "any non-terminal except `WAITING_CONFIRMATION`",
    from: NONTERMINAL_EXCEPT_WAITING_CONFIRMATION,
    to: "CANCELED",
    event: "task_canceled",
    condition: "Authorized cancellation",
    companions: [],
  },
  {
    id: "ANY_NONTERMINAL>SKIPPED:task_skipped",
    fromText: "any non-terminal",
    from: ALL_NONTERMINAL_TASK_STATES,
    to: "SKIPPED",
    event: "task_skipped",
    condition:
      'Policy-driven skip: dependency unsatisfied under `onDependencyUnsatisfied: "skip"`, or `misfire: "skip"` consumed the Task\'s occurrence',
    companions: [],
  },
  {
    id: "VALIDATING|WAITING_INPUT|READY|SCHEDULED|BLOCKED>FAILED:task_failed",
    fromText: "`VALIDATING`, `WAITING_INPUT`, `READY`, `SCHEDULED` or `BLOCKED`",
    from: ["VALIDATING", "WAITING_INPUT", "READY", "SCHEDULED", "BLOCKED"],
    to: "FAILED",
    event: "task_failed",
    condition:
      'A dependency terminalized without satisfying it under `onDependencyUnsatisfied: "fail"`',
    companions: [],
  },
] as const satisfies readonly TransitionRowData<TaskStateName>[];
